version: '3'
services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  backend:
    depends_on:
      - db
    build:
      context: ./backend
    container_name: backend
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/prod
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '8080:8080'