version: '3'
services:
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'