spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  profiles:
    active: dev

server:
  servlet:
    context-path: /api

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem