spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: ${POSTGRES_URL}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}

  profiles:
    active: dev